config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'index' => 'home#index', as: :index
  get 'latest' => 'home#latest', as: :latest

end

app/models/channel.rb
class Channel < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def latest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="index-banner" class="parallax-container">
	<div class="section no-pad-bot">
		<div class="container">
			<br><br>
			<h1 class="header center teal-text text-lighten-2">CekAntrian</h1>
				<div class="row center">
					<h5 class="header col s12 light">Maksimalkan waktu anda tanpa menunggu</h5>
				</div>
			<div class="input-field col s6 center">
				<input placeholder="Placeholder" id="first_name" type="text" class="validate">
			</div>
			<br><br>
		</div>
	</div>
	<div class="parallax"><img src="assets/spbu_1.jpg" alt="Unsplashed background img 1"></div>
</div>

<div class="container">
	<div class="section">
	<!--   Icon Section   -->
	<div class="row">
		<div class="grid-example col s12 card-panel header">Latest Channel</div>
	</div>
	<div class="row">
 		<div class="grid-example col s12 m6">
    			<div class="card-panel">
      				<span class="blue-text text-darken-2">Kesehatan</span>
					<ul ><% 5.times.each do%>
						<li>
							<div class="row valign-wrapper">
								<div class="col s3">
									<img src="assets/bank.png" alt="" class="responsive-img">
								</div>
								<div class="col s9">
									<span class="black-text">Bidan Rizki</span><br>
									<span class="black-text">9 antrian</span>
								</div>
							</div>
						</li><%end%>
					</ul>
    			</div>
 		</div>
 		<div class="grid-example col s12 m6">
			<div class="card-panel">
  				<span class="blue-text text-darken-2">SPBU</span>
					<ul ><% 5.times.each do%>
						<li>
							<div class="row valign-wrapper">
								<div class="col s3">
									<img src="assets/bank.png" alt="" class="responsive-img">
								</div>
								<div class="col s9">
									<span class="black-text">SPBU Kertijayan</span><br>
									<span class="black-text">Sepi</span>
								</div>
							</div>
						</li><%end%>
					</ul>
			</div> 
  		</div>
	</div>
	</div>
</div>


<div class="parallax-container valign-wrapper">
<div class="section no-pad-bot">
<div class="container">
<div class="row center">
<h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
</div>
</div>
</div>
<div class="parallax"><img src="assets/background2.jpg" alt="Unsplashed background img 2"></div>
</div>

app/views/home/latest.html.erb
<div class="container">
	<div class="section">
	<!--   Icon Section   -->
	<div class="row">
		<div class="grid-example col s12 card-panel header">Latest Channel</div>
	</div>
	<div class="row">
 		<div class="grid-example col s12 m6">
    			<div class="card-panel">
      				<span class="blue-text text-darken-2">Kesehatan</span>
					<ul ><% 5.times.each do |m|%>
						<li>
							<div class="row valign-wrapper">
								<div class="col s3">
									<img src="assets/bank.png" alt="" class="responsive-img">
								</div>
								<div class="col s9">
									<span class="black-text">a</span><br>
									<span class="black-text">10 antrian</span>
								</div>
							</div>
						</li><%end%>
					</ul>
    			</div>
 		</div>
 		<div class="grid-example col s12 m6">
			<div class="card-panel">
  				<span class="blue-text text-darken-2">SPBU</span>
					<ul ><% 5.times.each do%>
						<li>
							<div class="row valign-wrapper">
								<div class="col s3">
									<img src="assets/bank.png" alt="" class="responsive-img">
								</div>
								<div class="col s9">
									<span class="black-text">SPBU Kertijayan</span><br>
									<span class="black-text">Sepi</span>
								</div>
							</div>
						</li><%end%>
					</ul>
			</div> 
  		</div>
	</div>
	</div>
</div>


<div class="parallax-container valign-wrapper">
<div class="section no-pad-bot">
<div class="container">
<div class="row center">
<h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
</div>
</div>
</div>
<div class="parallax"><img src="assets/background2.jpg" alt="Unsplashed background img 2"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CekAntrian</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="<%= index_path%>" class="brand-logo">CekAntrian</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="<%= latest_path%>">Latest</a></li>
        <li><a href="#">Favorites</a></li>
        <li><a href="#">Login</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li class="no-padding"><a href="#">SPBU</a></li>
        <li class="no-padding"><a href="#">Rumah Makan</a></li>
        <li class="no-padding"><a href="#">Bank</a></li>
        <li class="no-padding"><a href="#">Klinik</a></li>
        <li class="no-padding"><a href="#">Transportasi</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

<%= yield %>

<footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l3 s12">
          <h5 class="white-text"></h5>
          <ul>
            <li><a class="white-text" href="#!">Privacy</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text"></h5>
          <ul>
            <li><a class="white-text" href="#!">Term</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text"></h5>
          <ul>
            <li><a class="white-text" href="#!">Help</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text"></h5>
          <ul>
            <li><a class="white-text" href="#!">Contact</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Provided by <a class="brown-text text-lighten-3" href="http://28labs.aplikasi.asia">28labs</a> with <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>
</body>
</html>